### ISSUE TITLE
timer bug#2

### ISSUE THREAD

**Issue by th3kumar** [th3kumar/Snoozz-Sleeping-Buddy#11]
When the `PlayerService` is playing and the timer is not set, and we navigate from `CustomActivity` to another activity (let's say `MainActivity`) and then return to `CustomActivity`, our "set timer" icon is gone; it should be visible.

**Comment by xvepkj** [comment]
Fixed this [here ](https://github.com/th3kumar/Snoozz-Sleeping-Buddy/pull/12)
