### ISSUE TITLE
Implement Communication Between Fragments

### ISSUE THREAD

**Issue by th3kumar** [th3kumar/Snoozz-Sleeping-Buddy#14]
**Description:**
In our Android app, we previously communicated between activities using the onActivityResult method. Now, we've migrated to using fragments, and we need to implement the same communication logic between HomeFragment and ComposeFragment. The goal is to replicate the functionality we had in the MainActivity and CustomActivity setup. We're looking for guidance and best practices on how to achieve this communication between fragments effectively.

Thank you!,

example:
```
override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)
        if (requestCode == REQUEST_CUSTOM_ACTIVITY) {
            hideLoadingAnimation()
        }

        if (requestCode == 123) {
            if (resultCode != RESULT_OK) {
                println("something went wrong updating...")
            }
        }
    }
```

**Comment by Kardelio** [comment]
Hmmmm sounds interesting, mind if i take this one?

**Comment by th3kumar** [comment]
> Hmmmm sounds interesting, mind if i take this one?

 Our repository will be honored to have your contribution. Good luck! @Kardelio

**Comment by Kardelio** [comment]
Awww very cool thank you!!! I'll probably have more questions in the near future but for now I'll get investigating :)

**Comment by Kardelio** [comment]
Can i ask possibly a silly question...

It looks to me like you arent actually passing any data between activities at the moment, so not sure what data should be communicated between fragments?
Is it just simply the fact that the "custom activity" has finished/closed that needs to be communicated?

**Comment by th3kumar** [comment]
> Can i ask possibly a silly question...
> 
> It looks to me like you arent actually passing any data between activities at the moment, so not sure what data should be communicated between fragments? Is it just simply the fact that the "custom activity" has finished/closed that needs to be communicated?

 We plan to remove the "custom activity" as we transition to ComposeFragment.

As ComposeFragment may have loading delays (due to excessive Exoplayer instances, which we'll address shortly🥲), we want to display a loading animation when transitioning to ComposeFragment from any other Fragment.
 (earlier we used onActivityResult, tho)

**Comment by Kardelio** [comment]
Ah ok! just to check, if we used a Shared ViewModel approach instead would that be ok? Or you would like to use the fragment alternative to this `result` api?

**Comment by th3kumar** [comment]
> Ah ok! just to check, if we used a Shared ViewModel approach instead would that be ok? Or you would like to use the fragment alternative to this `result` api?

Shared ViewModel would be great!

**Comment by Kardelio** [comment]
Ahhh ok coolio! <3

**Comment by th3kumar** [comment]
Hey @Kardelio ,

Thank you for your contribution and dedication to resolving this issue. We appreciate your effort.

We're in the process of making significant changes to the backend of the ComposeFragment, and these changes will address several issues, including the one you're currently working on. We kindly request your patience as we work towards the next update.

**For now, we would like to hold off on any further work on this particular issue.** However, we highly value your support and expertise, and **we'll definitely need your assistance with upcoming changes and new issues**. Your continued involvement is essential to our project's success.

Once again, thank you for your contributions, and we look forward to collaborating with you on the upcoming changes.
